language: python

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  - conda info -a
  - conda env create -f environment.yml
  - conda activate ttools
  - export PYTHONPATH=/home/travis/build/gregstarr/ttools
  - python -m pip install --upgrade pip
  - pip install coveralls
  
script:
  - coverage run --source=ttools -m pytest test/
  
notifications:
  email:
    on_success: never
    on_failure: never

after_success:
  - coveralls
