language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  
addons:
  apt:
    update: true
    packages:
    - gfortran

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - conda activate test-environment
  - conda env update -q -f environment.yml
  - cd ..
  - git clone https://github.com/rstoneback/pysatCDF.git
  - cd pysatCDF
  - python setup.py install
  - cd ../ttools
  - export PYTHONPATH=/home/travis/build/gregstarr/ttools
  - python -m pip install --upgrade pip
  - pip install coveralls
  
script:
  - coverage run --source=ttools -m pytest test/
  
notifications:
  email:
    on_success: never
    on_failure: never

after_success:
  - coveralls
