language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  
addons:
  apt:
    update: true
    packages:
    - gfortran

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  - conda info -a
  - conda env create -n test-environment python=$TRAVIS_PYTHON_VERSION -f environment.yml
  - conda activate test-environment
  - export PYTHONPATH=/home/travis/build/gregstarr/ttools
  - python -m pip install --upgrade pip
  - pip install coveralls gdown
  - mkdir -p test/test_tec_data
  - cd test/test_tec_data
  - gdown https://drive.google.com/uc?id=1tE6kLCmLMFulxhVu95gK8VVZNh0n-3hx
  - cd ../..
  
script:
  - coverage run --source=ttools -m pytest -v test/
  
notifications:
  email:
    on_success: never
    on_failure: never

after_success:
  - coveralls
