channels:
  - conda-forge
dependencies:
  - numpy==1.20.1
  - scipy==1.6.0
  - scikit-image==0.18.1
  - scikit-learn==0.24.1
  - bottleneck==1.3.2
  - pandas==1.2.1
  - pytest==6.2.2
  - h5py==3.1.0
  - cvxpy==1.1.0
  - pip
  - pip:
    - apexpy==1.0.3
    - pysatcdf==0.3.0

# install gurobi if possible, it is much faster, get a license then:
# python -m pip install -i https://pypi.gurobi.com gurobipy
