name: ttools
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - scikit-image
  - scikit-learn
  - bottleneck
  - pandas
  - pytest
  - h5py
  - cvxpy
  - pip
  - pip:
    - apexpy

# pysatcdf, leaving off because it's not working in CI

# install gurobi if possible, it is much faster, get a license then:
# python -m pip install -i https://pypi.gurobi.com gurobipy
