channels:
  - conda-forge
dependencies:
  - numpy==1.20
  - scipy==1.6
  - scikit-image==0.18
  - scikit-learn==0.24
  - bottleneck==1.3
  - pandas==0.24.2
  - pytest==6.2
  - h5py==3.1
  - cvxpy==1.1
  - pip
  - pip:
    - apexpy==1.0
    - pysatcdf==0.3.0

# install gurobi if possible, it is much faster, get a license then:
# python -m pip install -i https://pypi.gurobi.com gurobipy
