channels:
  - conda-forge
dependencies:
  - numpy
  - scipy==1.6
  - scikit-image
  - scikit-learn
  - bottleneck
  - pandas==0.24.2
  - pytest
  - h5py
  - cvxpy
  - pip
  - pip:
    - apexpy
    - pysat
    - pysatcdf==0.3.1

# install gurobi if possible, it is much faster, get a license then:
# python -m pip install -i https://pypi.gurobi.com gurobipy
