name: ttools
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - scipy
  - scikit-image
  - scikit-learn
  - bottleneck
  - pandas
  - pytest
  - h5py
  - cvxpy
  - matplotlib
  - seaborn
  - pip
  - pip:
    - apexpy
    - tables

# install gurobi if possible, it is much faster, get a license then:
# python -m pip install -i https://pypi.gurobi.com gurobipy

# optional:
# pysatcdf for SWARM files